### ISSUE TITLE
Add dockerignore

### ISSUE THREAD

**Issue by jonandernovella** [NBISweden/skuld#3]
Some files should probably not be bundled in the resulting docker image. A dockerignore file can help us with this.

**Comment by kusalananda** [comment]
The image only contains the four files `/usr/local/bin/skuld`, `/etc/group`, `/etc/passwd`, and `/etc/ssl/certs/ca-certificates.crt`.  These are explicitly copied into the scratch container from the build container.  The scratch container is empty from the start. There is nothing that needs to be ignored.
